language: cpp
compiler:
  - gcc 
  - clang
before_install:
  - sudo apt-add-repository -y ppa:j-4/vienna-rna
  - sudo apt-get update -q -y
  - sudo apt-get install -q -y vienna-rna
before_script:
  - autoreconf -i
