language: cpp

compiler:
  - gcc 
  - clang

before_install:
   - sudo apt-add-repository -y ppa:j-4/vienna-rna
   - sudo apt-add-repository -y ppa:ubuntu-toolchain-r
   - sudo apt-get update -q -y
   - sudo apt-get install -q -y vienna-rna
   - sudo apt-get install -q -y gcc-4.8 g++-4.8 clang 
   - sudo apt-get install -q -y help2man pkg-config gengetopt

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
  - autoreconf -i

script: ./configure && make && make check

