sudo: required
dist: trusty

language: cpp

compiler:
  - gcc 

before_install:
   - sudo apt-add-repository -y ppa:j-4/vienna-rna
   - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
   - sudo apt-get update -q -y
   - sudo apt-get install -q -y vienna-rna
   - sudo apt-get install -q -y help2man pkg-config gengetopt

before_script:
  - autoreconf -i

script: ./configure && make && make check

