language: cpp
compiler:
  - gcc 
  - clang
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
before_script:
  - autoreconf -i
script: ./configure && make && make check
addons:
  apt:
    sources:
      - ppa:j-4/vienna-rna
      - ubuntu-toolchain-r
    packages:
      - vienna-rna
      - help2man
      - pkg-config
      - gengetopt
      - gcc-5
      - g++-5
      - clang
